const foodData = [
  {
    name: "Steamed White Rice",
    category: "Rice",
    servingSize: 1,
    servingUnit: "cup",
    calories: 205,
    protein: 4.3,
    carbohydrates: 44.5,
    fat: 0.4,
    isFilipino: true,
  },
  {
    name: "Chicken Adobo",
    category: "Filipino Dishes",
    servingSize: 1,
    servingUnit: "serving",
    calories: 320,
    protein: 28,
    carbohydrates: 8,
    fat: 18,
    isFilipino: true,
  },
  {
    name: "Pork Adobo",
    category: "Filipino Dishes",
    servingSize: 1,
    servingUnit: "serving",
    calories: 360,
    protein: 23,
    carbohydrates: 8,
    fat: 25,
    isFilipino: true,
  },
  {
    name: "Sinigang na Baboy",
    category: "Filipino Dishes",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 310,
    protein: 25,
    carbohydrates: 12,
    fat: 18,
    isFilipino: true,
  },
  {
    name: "Sinigang na Hipon",
    category: "Filipino Dishes",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 220,
    protein: 24,
    carbohydrates: 10,
    fat: 9,
    isFilipino: true,
  },
  {
    name: "Tinolang Manok",
    category: "Filipino Dishes",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 240,
    protein: 27,
    carbohydrates: 9,
    fat: 11,
    isFilipino: true,
  },
  {
    name: "Tocino",
    category: "Filipino Dishes",
    servingSize: 1,
    servingUnit: "serving",
    calories: 250,
    protein: 16,
    carbohydrates: 12,
    fat: 15,
    isFilipino: true,
  },
  {
    name: "Longganisa",
    category: "Filipino Dishes",
    servingSize: 2,
    servingUnit: "pieces",
    calories: 300,
    protein: 15,
    carbohydrates: 12,
    fat: 21,
    isFilipino: true,
  },
  {
    name: "Bangus",
    category: "Fish",
    servingSize: 1,
    servingUnit: "serving",
    calories: 260,
    protein: 27,
    carbohydrates: 0,
    fat: 16,
    isFilipino: true,
  },
  {
    name: "Fried Egg",
    category: "Eggs",
    servingSize: 1,
    servingUnit: "piece",
    calories: 90,
    protein: 6,
    carbohydrates: 0.4,
    fat: 7,
    isFilipino: true,
  },
  {
    name: "Boiled Egg",
    category: "Eggs",
    servingSize: 1,
    servingUnit: "piece",
    calories: 78,
    protein: 6.3,
    carbohydrates: 0.6,
    fat: 5.3,
    isFilipino: true,
  },
  {
    name: "Pancit Canton",
    category: "Noodles",
    servingSize: 1,
    servingUnit: "serving",
    calories: 320,
    protein: 10,
    carbohydrates: 42,
    fat: 13,
    isFilipino: true,
  },
  {
    name: "Pancit Bihon",
    category: "Noodles",
    servingSize: 1,
    servingUnit: "serving",
    calories: 290,
    protein: 9,
    carbohydrates: 43,
    fat: 9,
    isFilipino: true,
  },
  {
    name: "Tapsilog",
    category: "Filipino Breakfast",
    servingSize: 1,
    servingUnit: "meal",
    calories: 620,
    protein: 29,
    carbohydrates: 65,
    fat: 27,
    isFilipino: true,
  },
  {
    name: "Bangsilog",
    category: "Filipino Breakfast",
    servingSize: 1,
    servingUnit: "meal",
    calories: 560,
    protein: 31,
    carbohydrates: 60,
    fat: 22,
    isFilipino: true,
  },
  {
    name: "Longsilog",
    category: "Filipino Breakfast",
    servingSize: 1,
    servingUnit: "meal",
    calories: 650,
    protein: 23,
    carbohydrates: 62,
    fat: 34,
    isFilipino: true,
  },
  {
    name: "Chicken Inasal",
    category: "Filipino Dishes",
    servingSize: 1,
    servingUnit: "serving",
    calories: 280,
    protein: 30,
    carbohydrates: 4,
    fat: 16,
    isFilipino: true,
  },
  {
    name: "Lechon",
    category: "Filipino Dishes",
    servingSize: 100,
    servingUnit: "g",
    calories: 360,
    protein: 27,
    carbohydrates: 0,
    fat: 28,
    isFilipino: true,
  },
  {
    name: "Kare-Kare",
    category: "Filipino Dishes",
    servingSize: 1,
    servingUnit: "serving",
    calories: 420,
    protein: 24,
    carbohydrates: 18,
    fat: 28,
    isFilipino: true,
  },
  {
    name: "Pinakbet",
    category: "Vegetables",
    servingSize: 1,
    servingUnit: "serving",
    calories: 180,
    protein: 7,
    carbohydrates: 18,
    fat: 9,
    isFilipino: true,
  },
  {
    name: "Ginisang Monggo",
    category: "Vegetables",
    servingSize: 1,
    servingUnit: "bowl",
    calories: 230,
    protein: 14,
    carbohydrates: 32,
    fat: 5,
    isFilipino: true,
  },
];

module.exports = foodData;